### ISSUE TITLE
[iOS] Compilation failed: org.jetbrains.kotlin.ir.descriptors.WrappedPropertyDescriptor@65076a4b 

### ISSUE THREAD

**Issue by avjiang** [korlibs/korio#105]
Hi, I have error thrown when building the project as Xcode framework

![image](https://user-images.githubusercontent.com/19270457/91254283-89b8ff00-e794-11ea-8efa-3f3f395036a1.png)

    Korio version: 1.11.13
    Kotlin version: 1.3.72

*project build.gradle*

      repositories {
        google()
        jcenter()
        maven { url "https://dl.bintray.com/korlibs/korlibs" }
        maven { url "https://kotlin.bintray.com/kotlinx" }
     }

*sharedCode build.gradle*

    kotlin {
    targets {
        final def iOSTarget = presets.iosX64 // Simulator

        fromPreset(iOSTarget, 'iOS') {
            binaries {
                framework('SharedCode')
            }
        }
        jvm("android") {
            compilations.main.kotlinOptions {
                jvmTarget = "1.8"
            }
        }
    }

      sourceSets {
        commonMain {
            dependencies {
                api 'org.jetbrains.kotlin:kotlin-stdlib-common'
                implementation "com.soywiz.korlibs.korio:korio:$korioVersion"
            }
        }

        iOSMain {
            dependsOn commonMain
            dependencies {
                implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime-native:$serialization_version"
            }
        }

        androidMain.dependencies {
            api 'org.jetbrains.kotlin:kotlin-stdlib'
            implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime:$serialization_version"
        }
    }
    }

Please assist thank you

**Comment by ArtRoman** [comment]
It's kotlinx.serialization issue, not korio: https://github.com/Kotlin/kotlinx.serialization/issues/768
Current workaround is to keep each abstract serializable class in single file with its serializable inherited classes.

**Comment by soywiz** [comment]
Still a Kotlin issue, not related to Korio. I'm closing the issue. But feel free to reopen if you think it is not the case
