### ISSUE TITLE
VfsFile#mkdirs

### ISSUE THREAD

**Issue by saket** [korlibs/korio#109]
Support for recursively creating directories would be very useful!

**Comment by soywiz** [comment]
https://github.com/korlibs/korio/blob/ee950bbd5591e8da6b623a3bee8dc81e69a8c293/korio/src/jvmMain/kotlin/com/soywiz/korio/file/std/LocalVfsJvm.kt#L384

mkdir is actually mkdirs. It should create all the directories missing

**Comment by saket** [comment]
Oh neat!

**Comment by saket** [comment]
Considering that the `mkdir` command has always created a single directory in most frameworks, it may be worth adding a `mkdirs` function with a `@ReplaceWith` to guide new korio users.

**Comment by saket** [comment]
Uhh I think there's some discrepancy between JVM and native implementation. JVM calls `mkdirs` whereas native calls `mkdir`: 

https://github.com/korlibs/korio/blob/bce382097b473cd082959b411b01f7bee8cc0215/korio/src/nativePosixMain/kotlin/com/soywiz/korio/cwd.kt#L7

**Comment by soywiz** [comment]
I see. Then that is a bug indeed. I think for node-based filesystems everything in the oath is created. But we might want to make mkdir working only on one level, and add the mkdirs version

**Comment by soywiz** [comment]
Latests versions already include the `mkdirs` function
