### ISSUE TITLE
Files returned by VfsFile#list() lose their absolute paths on native

### ISSUE THREAD

**Issue by saket** [korlibs/korio#111]
The files returned by `VfsFile#list()` seem to lose their absolute path on kotin/native. Here's a sample code that I'm running on macOS:

```kotlin
val directoryPath = "${tempVfs.absolutePath}/test"
val absPaths = rootLocalVfs[directoryPath].listSimple().map { it.absolutePath }
```

Assuming that there are some plain txt files present, `absPath` would contains `/file1.txt`, `/file2.txt`, etc. instead of their full paths from the root directory. Is this expected?

**Comment by soywiz** [comment]
Uhm. That is strange and looks like a but. That should only happen if the folder is jailed. Do you need the full path to interop with java? What is displayed if you print the VfsFiles from the list to string?

**Comment by saket** [comment]
Not really interop, but I'm using full path for other purposes in my project.

> That should only happen if the folder is jailed. 

Is this something I can check?

> What is displayed if you print the VfsFiles from the list to string?

The output is the same as if their path == absolutePath.
