### ISSUE TITLE
[LinuxX64] ld.lld: error: relocation R_X86_64_PC32 cannot be used against symbol __environ; recompile with -fPIC

### ISSUE THREAD

**Issue by enbandari** [korlibs/korio#114]
* Kotlin version: 1.4.10
* korio version: 2.0.0-alpha

```
    linuxX64 {
        binaries {
            compilations.getByName("main") {
                val matchInterop by cinterops.creating {
                    defFile("src/nativeInterop/cinterop/libmatch.def")
                    compilerOpts("-fPIC")
                }
            }
            sharedLib("match", listOf(RELEASE))
        }
    }
```

Execute :

```
./gradlew :libmatch:linkMatchReleaseSharedLinuxX64
```

Got error: 

```
ld.lld: error: relocation R_X86_64_PC32 cannot be used against symbol __environ; recompile with -fPIC
>>> defined in /home/bennyhuo/.konan/dependencies/target-gcc-toolchain-3-linux-x86-64/x86_64-unknown-linux-gnu/sysroot/lib64/libc.so.6
>>> referenced by out
>>>               /tmp/konan_temp7652478800042105268/result.o:(kfun:com.soywiz.korio.lang.Environment.$<init>$lambda-0$FUNCTION_REFERENCE$190.invoke#internal)
```

btw: :libmatch:linkMatchDebugSharedLinuxX64 will cause similar problem.

**Comment by soywiz** [comment]
Please, can you try with the final `2.0.0` compiled against Kotlin 1.4.20?

**Comment by enbandari** [comment]
I have tried 2.0.0-rc3 with Kotlin 1.4.20 ，same error.

**Comment by enbandari** [comment]
It's OK on macOS, seems a Linux related issue.

**Comment by enbandari** [comment]
Same problems on Kotlin 1.4.20 and Korio 2.0.0.

**Comment by soywiz** [comment]
2.0.0 was published, and was compiled and tested on ubuntu linux here: https://github.com/korlibs/korio/runs/1432436250?check_suite_focus=true
Which operating system are you trying on? Maybe that's a Kotlin/Native issue and `-fPIC` should be enabled?

The `__environ` global variable is used here:
https://github.com/korlibs/korio/blob/b4b02447c793cdbac5b4d5adb9c0d7795fd2a5d2/korio/src/nativePosixNonAppleMain/kotlin/com/soywiz/korio/lang/EnvironmentNativePosix.kt#L9

And it is the only way I'm aware of we have on posix to list the environment variables

**Comment by soywiz** [comment]
Reported here: https://youtrack.jetbrains.com/issue/KT-43502

But, please, can you indicate which environment do you have? Which operating system are you using, etc.

**Comment by enbandari** [comment]
Ubuntu 18.04. 

I am not sure how to enable -fPIC, I tried to add it to compilerOpts as below, but no effects.

```
    linuxX64 {
        binaries {
            compilations.getByName("main") {
                val matchInterop by cinterops.creating {
                    defFile("src/nativeInterop/cinterop/libmatch.def")
                    compilerOpts("-fPIC")
                }
            }
            sharedLib("match")
        }
    }
```

Maybe it is only a problem to build a shared library? I will try to push a demo to recurrent this. 

Thanks.

**Comment by enbandari** [comment]
It seems a bug of Kotlin compiler. Close.
