### ISSUE TITLE
Understanding path operations on LocalVfs

### ISSUE THREAD

**Issue by TheTeXnician** [korlibs/korio#117]
I'm trying to replace a custom MPP path implementation by korio and my test suite uncovered quite some details I can't really understand. I hope it's appropriate to ask these questions here to gain understanding for the workings of korio. For the start, I have two basic questions:

* The `LocalVfs["/"].pathInfo.isAbsolute()` returns `false` for me. Running `Paths.get("/").isAbsolute()` returns `true`. Is there a documentation about the differences in determining absolute paths?
* `Paths.get("/tmp/./test/..").getParent()` returns `/tmp/./test`, i.e. it does only consider path components for parenting. But with `LocalVfs["/tmp/./test/.."].parent` I already get the normalized result, i.e. `LocalVfs[""]`. Is there a way to get the path parent without normalization apart from trying things like `vfsFile.pathInfo.parts().dropLast(1).joinToString("/")` (which didn't work for me either)? For me, auto-normalization is quite unexpected, especially for relative paths.

**Comment by soywiz** [comment]
`Vfs` and `VfsFile` work differently than `Paths`. In the end they work like nodes in a filesystem that it is not required to be an actual local filesystem.

Alternatively you can use `PathInfo` instead, manipulate those inline instances, then use `rootLocalVfs` with the `PathInfo` when required. `VfsFile` is usually not that strict and might perform normalizations and other unexpected stuff if for example you are dealing with mountable filesystems and suff like t hat

**Comment by TheTeXnician** [comment]
Many thanks for the explanation. It's clearer now.
