### ISSUE TITLE
Import korio from commonMain (kotlin multiplatform).

### ISSUE THREAD

**Issue by Josef-Vonasek** [korlibs/korio#122]
I have `korio` in common dependencies:
```kotlin
    sourceSets {
        commonMain {
            dependencies {
                implementation("com.soywiz.korlibs.korio:korio:2.2.0")
            }
        }
    }
```
However, even though  `import com.soywiz.korio` works from `src/nativeMain` . It doesn't work in `src/commonMain`.

**Comment by soywiz** [comment]
Which gradle and kotlin versions are you using?

**Comment by Josef-Vonasek** [comment]
Gradle `7.0`. Kotlin `kotlin("multiplatform") version("1.5.20")`.

**Comment by soywiz** [comment]
Uhm. That looks reasonable. Can you provide an screenshot with your problem, showing the project files tree and the code not working? Is that imports are not available? Red code? Or something else?

**Comment by Josef-Vonasek** [comment]
I got around this by creating project with korge plugin from scratch.

**Comment by brizzbuzz** [comment]
I am getting the same problem :( 

<img width="1728" alt="Screen Shot 2022-01-20 at 11 44 00 AM" src="https://user-images.githubusercontent.com/5607577/150383134-100b3e3b-3ba6-480c-9e5e-4e07c7cc845b.png">

**Comment by soywiz** [comment]
@unredundant can you try the latest version and see if that way it reproduces? Latest version is `2.4.10` https://repo.maven.apache.org/maven2/com/soywiz/korlibs/korio/korio/2.4.10/
