### ISSUE TITLE
Downloading file from internet with UrlVfs.

### ISSUE THREAD

**Issue by Josef-Vonasek** [korlibs/korio#125]
I want to download a file with `UrlVfs`:
```kotlin
UrlVfs("https://raw.githubusercontent.com/korlibs/korio/master/README.md").copyTo(resourcesVfs["readme.md"])
```
1. This however creates a `readme.md` that doesn't contain the plain text I was expecting:
    ```
    �      �R]o�0}ƿ�� B�G���A���4M �\7q3'�l'���ݤ	��yp>��{N���y5�RQ9a�� 
    ^�,s,��w���X�ν¹�F����tE�i�0�����T��^%7v��J�ڲ�[�f+HM�*��%$fuBH\S=k̊�+?- 
    �F;%+�f_ ��3���·�WX(��l%L+~��Z�V�m����_�`����������
    |?y��E̡0b{�a��tq�O�ԕ�����T�䮱;���is�Uzg��mx�j�޹��! 
   ��&+�IZ�VTT��q��1ħV���_t��{��<�z�
    �7\M�b��*�g{?ݷ���$��̤M�ɺ^\��}�g���[� �΃�,��0<�p�? 
   9�����l��s�cgG���lW�R��iS�^��2�x���RC8��
   �a���)�^�����a��𻏭�m0���@H&jQe�JM����#�缍���іѫ��N��v�����  
    ```
2. It takes ~50 seconds to download this 3kb file.
3. It isn't possible to use custom headers.
4. Is there an easier way to track the download speed, bytes downloaded & bytes remaining, than using `readChunk` in `for` loop?

**Comment by Josef-Vonasek** [comment]
1. The problem is that the download encoding is `GZIP`. So it should be instead:
```
UrlVfs("https://raw.githubusercontent.com/korlibs/korio/master/README.md").copyTo(resourcesVfs["readme.gzip"])
```
Then I need to uncompress the file manually with
```
resourcesVfs["readme.gzip"].readBytes().uncompress(GZIP).toString(UTF8)
```

**Comment by Josef-Vonasek** [comment]
Any idea, why the download takes so long?

**Comment by soywiz** [comment]
Was not aware of that. Can you curl or wget with speed info and compare? Feel free to create a separate issue for that
