### ISSUE TITLE
Http requests on MingwX64 block forever.

### ISSUE THREAD

**Issue by Josef-Vonasek** [korlibs/korio#127]
Native http requests on windows block execution forever (like an infinite loop). 

```kotlin
println("A")
println(UrlVfs("https://raw.githubusercontent.com/korlibs/korio/master/README.md").readString())
println("B")
```
The above code will print `A` and nothing more (including exceptions).

**Comment by Josef-Vonasek** [comment]
However, `runBlockingNoJs { println(UrlVfs("https://raw.githubusercontent.com/korlibs/korio/master/README.md").readString()) }` is going to throw an exception.

**Comment by Josef-Vonasek** [comment]
@soywiz Any idea on how to debug this problem? It's a huge blocker.

**Comment by soywiz** [comment]
https is unsupported right now on native. There are a few issues in the bugtracker to implement it in some native targets. It is not planned for the shorterm. You might want to try another library in the meantime

**Comment by Josef-Vonasek** [comment]
Hm, could it then at least raise an exception in the meantime, instead of blocking forever?

**Comment by soywiz** [comment]
Sure. I have added a check that throws an exception on K/N Windows.

Related issue: https://github.com/korlibs/korio/issues/62
