### ISSUE TITLE
Use native stdout.

### ISSUE THREAD

**Issue by Josef-Vonasek** [korlibs/korio#133]
When I use `println` in a native binary (.exe), I don't get any output in terminal.

The binary was launched through the terminal.

**Comment by Josef-Vonasek** [comment]
The current workaround is to use logging. However, this won't log stderr from suspend functions!

**Comment by soywiz** [comment]
Can you provide a video showing the issue? Code used, and behaviour where you would expect to be printed?
It used to work for me at least

**Comment by Josef-Vonasek** [comment]
Actually, it works for `nativeDebug`.
