### ISSUE TITLE
Posix calls block main thread.

### ISSUE THREAD

**Issue by Josef-Vonasek** [korlibs/korio#134]
Performing a posix call from suspend function blocks the whole UI, until the call returns.
For example, the button in the following code will become unresponsive, once firefox is launched.

```kotlin
button(100.0, 100.0, 2.0, "Open Browser") {
  onClick { platform.posix.system("firefox") }
}
```

**Comment by soywiz** [comment]
That's expected.
KorGE event loop is single threaded. So coroutines are executed in the same thread in order. That's like in JS.
If you want to execute blocking stuff in a separate thread, you have to use a different dispatcher that uses threads.
For example:

```
onClick { withContext(Dispatchers.IO) { platform.posix.system("firefox") } }
```

**Comment by soywiz** [comment]
Also note that you can open urls with:

```
gameWindow.browse(URL("https://myurl/"))
```

**Comment by Josef-Vonasek** [comment]
I had a suspicion there would be a trick to it. However, I am not able to import `kotlinx.coroutines.Dispatchers.IO`. I can choose only from `Default, Main, Unconfined`.

The `browse` command is neat!

**Comment by Josef-Vonasek** [comment]
Maybe the special kotlinx [native-mt](https://github.com/Kotlin/kotlinx.coroutines/issues/462) should be used.

**Comment by soywiz** [comment]
I belive we should use `open` (linux/mac) and `CreateProcessW` (on windows)

**Comment by soywiz** [comment]
That covers this case: https://github.com/korlibs/korlibs-io/issues/12

If you cannot use a dispatcher, then you might want to use the worker API (what I'm using on KorIM and KorAU to offload reading/decoding from the main thread): https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.native.concurrent/-worker/

**Comment by Josef-Vonasek** [comment]
Worker doesn't seem to really fix that issue. The following code with still block the UI:
```kotlin
Worker.start().execute(TransferMode.SAFE, {}) { while (true) platofrm.posix._sleep(10000) }.consume({})
```

**Comment by soywiz** [comment]
You cannot use consume, since that blocks the thread executing it waiting for the result.

what you can do is to check if the future is completed in each frame.

```
val future = worker.start.execute
while (future.state != SCHEDULED) delay(1.milliseconds)
val result = future.result
```

**Comment by Josef-Vonasek** [comment]
I see. Btw, how does korge for example copy 1GB+ files without blocking main thread, despite the fact that kotlinx is single threaded on native?

**Comment by soywiz** [comment]
Using a worker:
https://github.com/korlibs/korio/blob/master/korio/src/nativeCommonMain/kotlin/com/soywiz/korio/file/std/LocalVfsNative.kt

**Comment by Josef-Vonasek** [comment]
I see. However, I am still not sure why the `while (future.state != SCHEDULED) delay(1.milliseconds)` doesn't block all the other coroutines.
