### ISSUE TITLE
Files with UTF8 are not supported on Windows.

### ISSUE THREAD

**Issue by Kesanov** [korlibs/korio#136]
It isn't possible to open a file that contains UTF8 characters (e.g.`ěščřžý áí`) on Windows (JVM doesn't seem to have issue).

**Comment by soywiz** [comment]
Woops :) This might break people installing apps in folders with unicode characters then. It seems that we are using a plain `fopen`

https://github.com/korlibs/korio/blob/e1ae02896db858ba043caf26aa49347e58e9e31e/korio/src/nativeCommonMain/kotlin/com/soywiz/korio/file/std/LocalVfsNative.kt#L63

I have to check if there is an unicode version. I thought that maybe for cinterop Kotlin serialized to utf-8, but maybe fopen uses another locale? or even the locale defined by the computer?

Which locale, codepage is your computer using?
