### ISSUE TITLE
Native `DynamicRootVfsVfs` incorrect `list()`.

### ISSUE THREAD

**Issue by Kesanov** [korlibs/korio#138]
Running an `C:\app\app.exe` from folder `C:\app\` with this code:
```kotlin
println(applicationVfs to applicationVfs.listSimple())
```
outputs
```kotlin
(DynamicRootVfsVfs[], (LocalVfs[], LocalVfs[], LocalVfs[/app.exe])
```
First, I have no idea why there is `LocalVfs[]`, as there are no additional files but `app.exe`.
Second, even the `LocalVfs[/app.exe]` is wrong. It should be `DynamicRootVfsVfs[/app.exe]` instead.

**Comment by Josef-Vonasek** [comment]
Also, what is an `DynamicRootVfsVfs`?

**Comment by Josef-Vonasek** [comment]
Redefining `listFlow` solves the problem:
```kotlin
    override suspend fun listFlow(path: String) = flow {
        val dir = opendir(resolve(path))
        if (dir != null) {
            try {
                while (true) {
                    val dent = readdir(dir) ?: break
                    val name = dent.pointed.d_name.toKString()
                    if (name != "." && name != "..")
                        emit(file("$path/$name"))
                }
            } finally {
                closedir(dir)
            }
        }
    }
 ```

**Comment by soywiz** [comment]
Didn't check, but the opendir, readdir and closedir APIs are synchronous, shouldn't we execute them in a separate worker?

**Comment by Josef-Vonasek** [comment]
Perhaps. However, the speed doesn't seem to be an issue.
