### ISSUE TITLE
Native:  `readFont` in `object` causes `InvalidMutabilityException`.

### ISSUE THREAD

**Issue by Josef-Vonasek** [korlibs/korio#139]
Loading a font in a global object causes the following error:
```kotlin
kotlin.native.concurrent.InvalidMutabilityException: mutation attempt of frozen com.soywiz.korim.font.TtfFont.Contour@3f08e9a8
```
The code:
```kotlin
object Assets {
  val font = runBlockingNoJs {
    try { cwd["font.ttf"].readFont() } catch (e: FileNotFoundException) {
       DefaultTtfFont
    }
  }
}
```

**Comment by soywiz** [comment]
I believe this issue should be issued in KorIM.

The explanation is that glyphs are computed on demand. That's incompatible with current Kotlin/Native memory model when storing as global objects.
If you plan to store a TTF font globally, you should either use `@ThreadLocal` or set the freeze param to try so all the glyphs are computed when loading. Check the declaration of DefaultTtfFont as an example of the freeze param:
https://github.com/korlibs/korim/blob/0c5d2fc8440605f4a558de1bc8934a9f55019d6d/korim/src/commonMain/kotlin/com/soywiz/korim/font/DefaultTtfFont.kt#L23
