### ISSUE TITLE
listSimple() is very slow

### ISSUE THREAD

**Issue by BioRyajenka** [korlibs/korio#141]
Hi,
I noticed that `listSimple()` takes 100ms in average even for single file! (not a dir). I didn't manage to understand why it is like that.

`listRecursiveSimple()` is also slow because it uses `listSimple()`. Adding explicit "if file" check to this function improves situation a bit, but not significantly.

I am using java 8 and OS windows. 
Also I noticed that under java 15 file operations work twice faster, but I'm not sure it is somehow related to the issue.

**Comment by soywiz** [comment]
Need more context: which korio version, HDD or SDD, which windows version?

**Comment by BioRyajenka** [comment]
korio `2.0.10`
sdd `Western Digital PC SN530 NVMe SSD`
Windows `10 Home 20H2`

**Comment by soywiz** [comment]
Thats a pretty old version. Can you try with the latest one `2.3.3`?

**Comment by BioRyajenka** [comment]
I tried (sorry, forgot to mention).
Same result

**Comment by BioRyajenka** [comment]
Another important thing I forgot to mention!
I have around 5000 files in the file tree, with around 10 files in each folder, and tree depth is around 5

**Comment by BioRyajenka** [comment]
100 ms is a result I get when list files/folders on the root of that tree

**Comment by soywiz** [comment]
Just tried  to reproduce it on a Win10 machine, with an SSD. The code:

```kotlin
val time = measureTime {
    localVfs("C:/temp").listSimple()
}
println("TIME: $time")
```

yields 1ms to me.

Korio 2.4.3, Windows 10, Java 8. Can you create a small project reproducing the issue, so there is more context?

**Comment by BioRyajenka** [comment]
I don't think creating the project will help, looks like the problem is in my computer's configuration. I tried to run the same code, here is result

![image](https://user-images.githubusercontent.com/9904421/137804763-ae01c3c0-99d7-4872-91c6-0b213ae57892.png)

**Comment by BioRyajenka** [comment]
Maybe it is worth to know that for not existing folders the result is the same (accidently run with "C:\temp" first, and I don't have "C:\temp")

**Comment by BioRyajenka** [comment]
Here is my build.gradle.kts
```kotlin
import com.soywiz.korge.gradle.*

buildscript {
    val korgePluginVersion: String by project
    val kotlinVersion: String by project

    repositories {
        mavenLocal()
        maven { url = uri("https://dl.bintray.com/korlibs/korlibs") }
        maven { url = uri("https://plugins.gradle.org/m2/") }
        mavenCentral()
        google()
    }
    dependencies {
        classpath("com.soywiz.korlibs.korge.plugins:korge-gradle-plugin:$korgePluginVersion")
        classpath(kotlin("serialization", kotlinVersion))
    }
}

apply<KorgeGradlePlugin>()
apply(plugin = "kotlinx-serialization")

dependencies {
    add("commonMainApi", "org.jetbrains.kotlin:kotlin-reflect:$kotlinVersion")
    add("commonMainApi", "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.3")
    add("commonMainApi", "org.jetbrains.kotlinx:kotlinx-serialization-json:1.1.0")
    add("commonMainApi", "org.jetbrains.kotlinx:kotlinx-datetime:0.1.1")

    add("commonMainApi", "co.touchlab:stately-common:1.1.4")
    add("commonMainApi", "co.touchlab:stately-concurrency:1.1.4")
    add("commonMainApi", "co.touchlab:stately-isolate:1.1.4-a1")
}

korge {
    id = "com.sample.demo"
}
```

and here is my gradle.properties
```properties
korgePluginVersion=2.0.9.1
kotlinVersion=1.4.30
org.gradle.jvmargs=-Xmx2g
```

**Comment by BioRyajenka** [comment]
When I run 1000 iterations, I got only 0.1 ms for 1 iteration
![image](https://user-images.githubusercontent.com/9904421/137805560-47f694c6-1808-4825-9b99-31778f74d2c2.png)

Looks like jit doing its job :)
![image](https://user-images.githubusercontent.com/9904421/137805780-9ba1ef8c-2019-413c-bd09-7407a30f3ac7.png)

**Comment by BioRyajenka** [comment]
Ok, the slowest part probably is not `listSimple()`, but creating a localVfs
![image](https://user-images.githubusercontent.com/9904421/137815596-39d1e9ae-22b5-408b-9bf4-996ddfce73ce.png)

**Comment by soywiz** [comment]
Then can we close this issue?

**Comment by BioRyajenka** [comment]
Actually, this is still issue for me (100ms for file is not ok), but lets close it. I will reopen when have more details.
Thanks for your time
