### ISSUE TITLE
Kotlin Native 

### ISSUE THREAD

**Issue by jan-tennert** [korlibs/korio#142]
Sorry if this is a stupid question but I cant test it right know are websockets available for kotlin native?

**Comment by soywiz** [comment]
I believe they are available. But only ws:// not wss:// because secure sockets are not implemented on native right now

**Comment by jan-tennert** [comment]
Hm ok thanks

**Comment by soywiz** [comment]
@jan-tennert is that enough for your case, or would you need secure sockets? This is the related task: https://github.com/korlibs/korio/issues/62

In the case you need it, which kotlin native targets would you need? Windows, linux, mac, or ios?

**Comment by jan-tennert** [comment]
Im making a multiplatform Discord API wrapper and I wanted to use Korio for the gateway (websocket) connection and also for http requests. But I think their websocket is available for ws but im not sure

**Comment by jan-tennert** [comment]
If yes korio as well as klock would fit perfectly in my project
