### ISSUE TITLE
Multiplatform not working

### ISSUE THREAD

**Issue by jan-tennert** [korlibs/korio#144]
I tried to implement korio in my multiplatform project, but it removes all IJ modules (probably because something went wrong?). Removing the dependency brings back these modules. Other MP project like kotlin serialization, ktor etc work perfectly. I have a video about it:

https://user-images.githubusercontent.com/26686035/132606492-c58cf4ba-a3a9-4af7-87a6-b560a821f426.mp4

**Comment by jan-tennert** [comment]
Ok this only happens if I use a higher version than 2.2.1. Weird

**Comment by soywiz** [comment]
Which gradle version are you using?

**Comment by jan-tennert** [comment]
7.1.1

**Comment by jan-tennert** [comment]
just tested it same with klogger and klock

**Comment by jan-tennert** [comment]
Just for clarification: Maven Central says the latest version is 2.4.1, github latest release is 2.2.1. Is that right?

**Comment by soywiz** [comment]
Sorry for the delay
Development for all the korlibs libraries happens now on https://github.com/korlibs/korge-next that’s why latest version is 2.4.1.
I don’t really know what’s happening there just by looking at the video, build.gradle might be different in your case but in other projects I didn’t have that problem. Gradle version seems fine too.
