### ISSUE TITLE
Can't connect to websocket

### ISSUE THREAD

**Issue by jan-tennert** [korlibs/korio#145]
So I tried to connect to a websocket and if I try to connect with **ws://localhost:2333** then it just immediately disconnects and with **wss://localhost:2333** it gives me a **javax.net.ssl.SSLException: Unsupported or unrecognized SSL message**. (tested on JVM). You can test it yourself by downloading https://github.com/freyacodes/Lavalink#server-configuration, starting the server and connect via korio, maybe I'm just stupid. Connecting to another websocket works, maybe something is incompatible?

**Comment by jan-tennert** [comment]
Just tried connecting with Postman, that works flawlessly

**Comment by jan-tennert** [comment]
Ah nvm wss can't work. But that doesn't fix my problem with non-secure

**Comment by soywiz** [comment]
This might have been fixed here: https://github.com/korlibs/korge-next/commit/3d24d5820aaa8246db958465e3d7225dcb362a70
