### ISSUE TITLE
Does the HttpClient always use a secure socket?

### ISSUE THREAD

**Issue by jan-tennert** [korlibs/korio#146]
I tried to make a request to a website but I always get an error that secure sockets aren't available on platform XY. Is that normal? (The url doesn't matter, I can set "test" as url and I get the same error)

**Comment by soywiz** [comment]
It was implemented on Windows sometime ago.

* Now in linux: https://github.com/korlibs/korge-next/commit/b32d44968fdc5db10018c80b6204fe6b867cd2e4
* Mac and apple devices: https://github.com/korlibs/korge-next/commit/7e78829322f68dee66a127bc80106f7e1e37bd47
