### ISSUE TITLE
Router returns status 200 OK when no route found

### ISSUE THREAD

**Issue by gerfigna** [korlibs/korio#15]
... instead 404 Not Fount

**Comment by soywiz** [comment]
Can you provide an example? Here is a test where it yields a 404:
https://github.com/korlibs/korio/blob/7d54949eae107c85b3c22ccb22015c16c1306ffa/korio-ext-web/src/test/kotlin/com/soywiz/korio/ext/web/router/KorRouterTest.kt#L93
