### ISSUE TITLE
Debug Flag

### ISSUE THREAD

**Issue by faweizz** [korlibs/korio#154]
There is a property in Kotlin/Native https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.native/-platform/is-debug-binary.html

It would be an Option to add the Flag to https://github.com/korlibs/korge-next/blob/main/korio/src/commonMain/kotlin/com/soywiz/korio/util/OS.kt

Additonally, Korge could display the current target in the debug overlay.

Other frameworks (i.e. Spring boot & application.properties) support loading of configuration parameter sets based on the application target. This would help to create setups where the application is staged between multiple environments.

**Comment by soywiz** [comment]
Implemented, please create a separate issue for application variants
