### ISSUE TITLE
What license?

### ISSUE THREAD

**Issue by vemilyus** [korlibs/korio#23]
## What is the exact license for Korio? 

Right now the [Contributing](https://korlibs.github.io/contributing/) page just states some marketing terms like `free of charge` or `suggest changes` but no actual license.

Personally I would recommend the `Apache 2.0 License` or `BSD 3-clause` licenses, as they provide the most freedom without the cancer that is "copyleft".

**Comment by soywiz** [comment]
Hey vemilyus. First of all: Im not alicense expert.

I have written most of the code from scratch and that allows me to be more flexible. From my side all my code could be public domain. But some parts from some kor libraries are ports or ar based om other libraries. I would try a MIT license first, or an apache2 license later. I have tried to always provide my sources when ported something. I still have to do a full audit to all libraries to provide the most flexible license at the right level or to rewite some stuff from scratch if required to not have to propagate restrictful licenses. I find the auditing part/propagating a bit boring and will take some time, so any help here would be very welcome :)
