### ISSUE TITLE
Websockets clients doenst work

### ISSUE THREAD

**Issue by IgorKey** [korlibs/korio#25]
Hi there! I've just try to use your websocket multiplatform and got a lot of queestions.
First of all, you have a ignored test for com.soywiz.korio.net.ws.WebSocketTest. If I try to change the implementation, I always stay in infinity loop in com/soywiz/korio/net/ws/RawSocketWebSocketClient.kt#connect:127
Secondly: implementation for windows doesn't work at all. I had to change something in com.soywiz.korio.net.NativeSocket#connect, and I want to discuss it :) 
 All of this situation seems strange. May be I dont understand some approaches...))) Please give me feedback ASAP

**Comment by soywiz** [comment]
Probably I missed it.

If you have a fix for it, I suggest you to make a PR :)
Also, let me know which approaches you don't understand and I'll try to help / change it if it doesn't make sense.

**Comment by IgorKey** [comment]
The coroutineScope block is block mode block. So In com.soywiz.korio.net.ws.RawSocketWebSocketClient#connect we always block the return method of WebSocketClient.. So, we'll never get the instance of WebSocketClient. Why? How it should be work?

**Comment by soywiz** [comment]
https://github.com/korlibs/korio/blob/07361b38af935dfaa770ab9c1dbec8232b577249/src/commonMain/kotlin/com/soywiz/korio/net/ws/RawSocketWebSocketClient.kt#L96-L124

It opens an HTTP connection and switches to websocket protocol, then reads all the headers from the server, and then does a launch (that should return immediately), that launch handles the connection in a separate coroutine, so it shouldn't block

**Comment by IgorKey** [comment]
coroutineScope blocks till coroutines (launch) inside it won't end.. Oh, I don't understand it... May be we discuss it via skype?( :) )
Because I have a lot of changes for do it alive...

**Comment by soywiz** [comment]
Sorry, not sure why I missed this. Even if they are a lot of chages, PRs are welcome.

**Comment by Syrou** [comment]
Should this issue not be fixed with the latest coroutines? I think they recently fixed this?

**Comment by soywiz** [comment]
I have tried to update to Kotlin 1.3.30, so far my other libraries without dependencies work, but this one depending on kotlinx.coroutines fails hard. They have changed the artifact names, and I have updated and everything seems fine but when compiling native artifacts `kotlinx.coroutines` package seems to not be found. I planned to update all the libraries today, but with this problem I cannot do much about it sadly. I'll investigate further this week.
https://github.com/korlibs/korio/blob/c06bc940372a1a7fecf3930e5560a3a81a81fe2e/korio/build.gradle#L11
https://travis-ci.org/korlibs/korio/jobs/520054747

**Comment by IgorKey** [comment]
Hi. I know how to solve this problem. Could you please publish the 
	com.soywiz:klock:$klockVersion
	com.soywiz:kmem:$kmemVersion
	com.soywiz:kds:$kdsVersion

Dependencies. As I've understood, you built it only for mavenLocal

**Comment by IgorKey** [comment]
idea patch
[[WORKAROUND_for_soywiz]_Move_to_1_3_30.txt](https://github.com/korlibs/korio/files/3100043/WORKAROUND_for_soywiz._Move_to_1_3_30.txt)

**Comment by soywiz** [comment]
If this was the issue that caused tcpclient to fail on windows, it is fixed already. So I'm closing it. Feel free to reopen if it is not the case.
