### ISSUE TITLE
KN multi-threading problems

### ISSUE THREAD

**Issue by IgorKey** [korlibs/korio#26]
There are a lot of static members which doesn't mark as @ThreadLocal or @SharedImmutable. So, sometimes in multi-threading env we get an exception like this: **Trying to access top level value not marked as @ThreadLocal or @SharedImmutable from non-main thread**. Are you planning to solve these problems?

**Comment by soywiz** [comment]
I was not aware of those problems. If you have a few examples, that would help. Also PRs are welcome

**Comment by IgorKey** [comment]
So. There are a lot of areas. E.g. all of fields in **com.soywiz.korio.file.std.LocalVfsNative** should be marked as @ThreadLocal or @SharedImmutable if they called from non-main thread...

I do some "random"(ThreadLocal) fixes in my cloned repo, and ofc this work, but I think we need more complex and thoughtful decision

**Comment by soywiz** [comment]
Unfortunately this is too ambiguous and no specific to be done ( https://en.wikipedia.org/wiki/SMART_criteria ).
If you have a specific area that you know it is failing on native, please create a separate issue. Ideally with a failing test or code that I can use to be aware of the specific issue.
