### ISSUE TITLE
Can't seem to use the library on mingw?

### ISSUE THREAD

**Issue by Syrou** [korlibs/korio#28]
Using Gradle 4.10 with enableFeaturePreview('GRADLE_METADATA') with id 'kotlin-multiplatform' version '1.3.20'

and this dependency setup
```
     mingwMain {
            dependencies {
                implementation "org.jetbrains.kotlin:kotlin-stdlib"
                implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core-native_debug_mingw_x64:1.1.1"
                implementation "com.soywiz:korio:0.20.0"
                implementation "org.jetbrains.kotlinx:atomicfu-windows64:0.12.2"
            }
        }
```
Kotlin does for the mingw code does not seem to find korio related things at all? Any pointers?

**Comment by Syrou** [comment]
This is the repo: https://github.com/Syrou/Padame

**Comment by soywiz** [comment]
Korio is now 1.6.4. List of versions here: https://bintray.com/soywiz/soywiz/korio

Starting with 1.6, metadata is not included, but you have to provide each dependency for each target manually:
More info here:
https://korlibs.soywiz.com/faq/

I still have to update the readme to reflect this, but Ill try to update it this weekend.

**Comment by Syrou** [comment]
I added that bintray maven to repositories and bumped the versions + removed metadata from settings.gradle

Now I Get:
```
* What went wrong:
Could not resolve all files for configuration ':mingwCompileKlibraries'.
> Could not resolve com.soywiz:korio-metadata:1.6.4.
  Required by:
      project :
   > Could not resolve com.soywiz:korio-metadata:1.6.4.
      > Could not parse POM https://bintray.com/soywiz/soywiz/korio/com/soywiz/korio-metadata/1.6.4/korio-metadata-1.6.4.pom
         > The markup in the document preceding the root element must be well-formed.
> Could not resolve com.soywiz:korio-mingwx64:1.6.4.
  Required by:
      project :
   > Could not resolve com.soywiz:korio-mingwx64:1.6.4.
      > Could not parse POM https://bintray.com/soywiz/soywiz/korio/com/soywiz/korio-mingwx64/1.6.4/korio-mingwx64-1.6.4.pom
         > The markup in the document preceding the root element must be well-formed.
```

**Comment by soywiz** [comment]
This is the right maven repository. The other url is for viewing versions:
https://dl.bintray.com/soywiz/soywiz

For the reference, in my projects i configure the repositories here:
https://github.com/korlibs/korio/blob/master/buildSrc/src/main/kotlin/com/soywiz/korlibs/modules/Repositories.kt

**Comment by Syrou** [comment]
Thanks for pointing out my misstakes :) Can add the library now
