### ISSUE TITLE
TcpClient in windows seems to have issues

### ISSUE THREAD

**Issue by Syrou** [korlibs/korio#29]
Korio version=1.6.4

Using this simple code:

```
    GlobalScope.async {
        val tcpClient = createTcpClient(false)
        tcpClient.connect("172.65.204.172", 12995)
        if(tcpClient.connected){
            println("We are connected!")
            tcpClient.write(dataBytes)
            val result = tcpClient.readAll()
        }
    }
```
Will casts kotlin.IllegalStateException: WSA error(connect): 10051 on Windows.
This will work on mac, but instead it does not seem to write/read any of the data the server should get/send back

**Comment by Syrou** [comment]
Seems to have to do with the fact that host input is not supporting IP-adress in the library now

**Comment by Syrou** [comment]
Seems to have problem with the recieving the same way when running on mac

**Comment by soywiz** [comment]
Sorry for the huge delay, the last weekend and this week I have been pretty busy. I plan to work on fixing stuff this weekend, so I'll have a look on this!

**Comment by IgorKey** [comment]
[This is](https://github.com/korlibs/korio/issues/25) the same issue, I think.

**Comment by Syrou** [comment]
@soywiz Any news?

**Comment by soywiz** [comment]
Sorry for the delay. I have been focusing on the first preview of korge-3d. Now that it is out, I'll review all the projects and will try to fix all the issues. Probably this weekend.

**Comment by Syrou** [comment]
@soywiz Did your latest migration to latest kotlin help this at all?

**Comment by Syrou** [comment]
Also seems that you need to run:
platform.windows.WSAStartup(...)
platform.windows.WSACleanup()

on windows in order to actually setup a proper socket with winsockets
