### ISSUE TITLE
How to manipulate local files?

### ISSUE THREAD

**Issue by 9468305** [korlibs/korio#30]
Hi,

`korio` is awesome! But I still didn't find out how to manipulate local files.
I suppose maybe in someway like `VfsFile("path").writeText("content")`?
Could you please show me some clues or sample code?

Thank you!

**Comment by soywiz** [comment]
You can use:
```
"file:///path/to/my/file".uniVfs
localVfs("/path/to/my/file")
localCurrentDirVfs["../../file.txt"]
localCurrentDirVfs[".."].jail()["file.txt"]
```

**Comment by 9468305** [comment]
Thanks.
