### ISSUE TITLE
Kotlin 1.30.31

### ISSUE THREAD

**Issue by IgorKey** [korlibs/korio#31]
Hi there! What is the status of 1.3.30-31 upgrade?:)
Are you have some plans for it?..

**Comment by soywiz** [comment]
I wanted to update this stuff, but I had several issues and bugs when compiling against `1.3.3x`. They have to be addressed first. I am pretty busy these days, but I will try again when I have time again unless someone does it before and makes a PR

**Comment by IgorKey** [comment]
Yes, I know. I can solve only few of them. If you agree with partially PR, I'll create it.

**Comment by soywiz** [comment]
Please, do it. Any advance is welcome 👍

**Comment by IgorKey** [comment]
@soywiz ,Carlos look at this please... https://github.com/korlibs/korio/pull/32
