### ISSUE TITLE
Some problem with linux target.

### ISSUE THREAD

**Issue by IgorKey** [korlibs/korio#36]
Hi, @soywiz. I got some problem when trying to create shared library from your korio linux part.

`ld.lld: error: relocation R_X86_64_PC32 cannot be used against symbol __environ; recompile with -fPIC
>>> defined in /Users/igor_kuzminykh/.konan/dependencies/target-gcc-toolchain-3-linux-x86-64/x86_64-unknown-linux-gnu/sysroot/lib64/libc.so.6
>>> referenced by Types.kt:187 (/Users/teamcity/buildAgent/work/4d622a065c544371/Interop/Runtime/src/main/kotlin/kotlinx/cinterop/Types.kt:187)
>>>               /var/folders/81/1x8w9mxd38n8ynv7r2z3vfdh0000gp/T/konan_temp6619027810560038268/result.o:(platform_posix_kniBridge42)
e: /Users/igor_kuzminykh/.konan/dependencies/clang-llvm-apple-8.0.0-darwin-macos/bin/ld.lld invocation reported errors`

Do you know what specific things can breed this error? I investigate your repo and didn't find any specific things for build linux. May be it related with your CI env?

**Comment by soywiz** [comment]
Never had this issue. But seems to be kotlin/native or kotlinx.coroutines? (Kotlinx) issue:

/Users/teamcity/buildAgent/work/4d622a065c544371/Interop/Runtime/src/main/kotlin/kotlinx/cinterop/Types.kt

**Comment by IgorKey** [comment]
Hmm... thanks for point. I'll try to investigate it

**Comment by soywiz** [comment]
I have been using linux lately and didn't find this issue. Also it seems to compile fine on travis. Feel free to reopen if this issue persists on the latest version and you find a reproducer
