### ISSUE TITLE
JVM Test error : java.nio.channels.UnresolvedAddressException

### ISSUE THREAD

**Issue by lemkoleg** [korlibs/korio#49]
Hello. Tell me why I get this JVM Test error when I try to get WebSocketClient:
val url = "ws://localhostname:3456"
val c: WebSocketClient  = RawSocketWebSocketClient(url,null, null, null, false)
...java.nio.channels.UnresolvedAddressException
	at sun.nio.ch.Net.checkAddress(Net.java:101)...
	
	
And one more thing: can I get RawSocketWebSocketClient из WebSocketClient ? For instance:
val url = "ws://localhostname:3456"
val c: RawSocketWebSocketClient = RawSocketWebSocketClient(url,null, null, null, false) as RawSocketWebSocketClient

**Comment by soywiz** [comment]
Shouldn't it be `ws://localhost:3456`? Maybe that's why it is not resolved

**Comment by lemkoleg** [comment]
"localhostname" - name of local host. 
it is not right? But I'll try "localhost"

**Comment by soywiz** [comment]
Try `ws://localhost:3456` or `ws://127.0.0.1:3456`

**Comment by lemkoleg** [comment]
And one more thing: can I get RawSocketWebSocketClient из WebSocketClient ? For instance:
val url = "ws://localhostname:3456"
val c: RawSocketWebSocketClient = RawSocketWebSocketClient(url,null, null, null, false) as RawSocketWebSocketClient
and work like with RawSocketWebSocketClient?

**Comment by benny1611** [comment]
Hi, I have the same problem when trying to open a socket to ```localhost```.
I have this function:
```
var webSocketClient : WebSocketClient? = null
try {
    println("Connecting to: ws://$host:$port")
    webSocketClient = WebSocketClient("ws://$host:$port")
} catch (e: Exception) {
    e.printStackTrace()
    logger.fatal { e.message }
    return false
}
```
And when I run this code I get the following error:
```
Connecting to: ws://localhost:9002

java.nio.channels.UnresolvedAddressException
......

```

Can you tell me what I'm doing wrong?

**Comment by soywiz** [comment]
Does `ws://127.0.0.1:9002` work for you instead?

**Comment by benny1611** [comment]
```
Connecting to: ws://127.0.0.1:9002

java.nio.channels.UnresolvedAddressException
```

**Comment by soywiz** [comment]
That's strange. Are you fully sure that you have that port listening and it is listening to the right interface?

https://docs.oracle.com/javase/8/docs/api/java/nio/channels/UnresolvedAddressException.html

Trying to open a telnet to that port works for you?

```
telnet 127.0.0.1 9002
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
```

**Comment by benny1611** [comment]
Tried to telnet to ```127.0.0.1 9002``` and I've got this on teh server side:

```
Socket Accept
Got new device on fd 920
New Connection established on slot 5
Socket connected
```

**Comment by benny1611** [comment]
It works when I use ```AsyncClient``` but I want to use this code in a multi-platform project (```js``` and ```jvm```). As far as I understand ```AsyncClient``` does not work in browser js as stated in the description: 
```
Korio includes a TCP client (implementing AsyncStream) and a TCP server with a lazy asynchronous connection iterator for all supported platforms but browser javascript.
``` 
Example code that works:
```var clientAsynch: AsyncClient = createTcpClient(host, port, false)```

**Comment by benny1611** [comment]
If I use ```AsyncClient```, I can build the project with no errors, but when I try to run it I get the following error in the console of the browser :
 ```ReferenceError: require is not defined ..................... korio-root-korio.js:47299:3``` 
That's why I changed now to the ```WebSocketClient```

**Comment by soywiz** [comment]
`RawSocketWebSocketClient` uses `AsyncClient`, that is available on node.js but not on the browser.
`WebSocketClient` uses native `WebSocket` on Browser, and `RawSocketWebSocketClient` on the other targets.

**Comment by benny1611** [comment]
Ok, but how can I get it working? Do you have any idea what might be wrong and why I get the ```UnresolvedAddressException```? (or am I just doing something wrong?)

**Comment by lemkoleg** [comment]
are you using the latest release?

пт, 12 июн. 2020 г., 12:50 benny1611 <notifications@github.com>:

**Comment by benny1611** [comment]
I'm using this version:

```implementation "com.soywiz.korlibs.korio:korio-jvm:1.10.2"```

**Comment by lemkoleg** [comment]
Try 1.11.5 minimum

пт, 12 июн. 2020 г., 12:55 benny1611 <notifications@github.com>:

**Comment by lemkoleg** [comment]
Or last relise 1.11.8

пт, 12 июн. 2020 г., 12:55 benny1611 <notifications@github.com>:

**Comment by benny1611** [comment]
Ohhh, yeah. Turns out I'm just using a very old version if ```korio```. Thank you very much!
