### ISSUE TITLE
TypeError: this.resultContinuation_0 is undefined...

### ISSUE THREAD

**Issue by lemkoleg** [korlibs/korio#51]
Hello. I am trying to use WebSocket in my project.
But, the compiled JS script in the browser gives me such an error.
Here is my code:

private const val STANDART_TIME_OUT: Double = 5000.0
private       val STANDART_TIME_OUT_SPAN = TimeSpan(STANDART_TIME_OUT)

class Connection(u: String) {
    private val url = u
    private lateinit var myConnection    :Deferred<Unit>
    private lateinit var mySocketChannel :WebSocketClient
    private lateinit var signalonOpen    :Signal<Unit>
	
	init {
        if(connectionDNSName.isNotEmpty()){
            myConnection = GlobalScope.async{ setConn() }}
        }
	}
	
	 private suspend fun setConn(){
        try {
            mySocketChannel = WebSocketClient(url,null,null,"",false)
            signalonOpen = MySocketChannel.onOpen
        }
        catch (e: Exception)
        {
            println(e.toString())
        }
    }
	
	@JsName("waitConn")
    suspend fun waitConn(){
        signalonOpen.waitOne(STANDART_TIME_OUT_SPAN)
    }
	
	@JsName("send_data")
    suspend fun send_data(){
        if(myConnection.isActive)
            {myConnection.await()}
		mySocketChannel.send("Hello Soywiz")
	}
	
And here is how I try to use this cad in the browser:

   <!DOCTYPE HTML>
     <html>
       <head>
          <meta charset="UTF-8">
       </head>
	   
       <body>
          <p>Before script...</p>
		  <script src="MyProect.js"></script>
	      <script type="text/javascript">
		      async function f() {
			     var c = new myProectName.Connection("localhost",22236);
				 c.waitConn();
				 c.send_data();}
			  f();
		   </script>
		   <p>...After script</p>
       </body>
    </html>
	
	
Here is the error I get:

  TypeError: this.resultContinuation_0 is undefined...

I found that this is due to calls to wait functions. Maybe I'm doing something wrong?

**Comment by soywiz** [comment]
Did you solve this?

**Comment by lemkoleg** [comment]
No. I got around the problem differently. I made the Connection class inherited from CoroutineScope.
And I launched myConnection.await () call using a new thread:

class Connection(u: String) {
private val url = u
private lateinit var myConnection :Deferred
private lateinit var mySocketChannel :WebSocketClient
private lateinit var signalonOpen :Signal
override val coroutineContext: CoroutineContext = Dispatchers.Unconfined
private  val myContext = CoroutineScope(coroutineContext)

init {
    if(connectionDNSName.isNotEmpty()){
        myConnection = GlobalScope.async{ setConn() }}
    }
}

 private suspend fun setConn(){
    try {
        mySocketChannel = WebSocketClient(url,null,null,"",false)
        signalonOpen = MySocketChannel.onOpen
    }
    catch (e: Exception)
    {
        println(e.toString())
    }
}

@JsName("send_data")
suspend fun send_data(){
    MyContext.writer{
    if(myConnection.isActive)
        {myConnection.await()}
	mySocketChannel.send("Hello Soywiz")
	}
}

**Comment by soywiz** [comment]
Actually you cannot call `suspend fun` functions directly from JS. You should probably create a function that returns a Promise or something. Korio provides a promise class that uses real Promise from JS: https://github.com/korlibs/korio/blob/f633ec016af6c3368ed200b475131c39dd8bc334/korio/src/commonMain/kotlin/com/soywiz/korio/async/Promise.kt#L13

Because probably internally `suspend fun` are receiving a parameter with the context/continuation to be called after the function is completed, and to have the context attached.
