### ISSUE TITLE
uncaught exception: NotImplementedError: An operation is not implemented: onBinaryMessage, onAnyMessage

### ISSUE THREAD

**Issue by lemkoleg** [korlibs/korio#54]
Hello. When I try to read the message in a compiled JS file, I get the following error:

uncaught exception: NotImplementedError: An operation is not implemented: onBinaryMessage, onAnyMessage

Can't do it? Here is my code:

myWebSocket = WebSocketClient(url,null,null,"",false)
signalonOpen = MyWebSocketChannel!!.onOpen
signalonBinaryMessage = MyWebSocketChannel!!.onBinaryMessage
val buf = signalonBinaryMessage?.waitOne(timeout = t);

**Comment by lemkoleg** [comment]
I found that this exception is thrown when calling a function MyWebSocketChanne.send(ByteArray). The answer is not readable. I can’t understand what I’m doing wrong.

**Comment by lemkoleg** [comment]
It seems to me, or are these methods not really implemented?

**Comment by soywiz** [comment]
https://github.com/korlibs/korio/blob/d7be449a6867928528479c68225fb095f3212e23/korio/src/jsMain/kotlin/com/soywiz/korio/net/ws/WebSocketsJs.kt#L44
