### ISSUE TITLE
KorRouter.registerRouter error on GET requests

### ISSUE THREAD

**Issue by Nestorferrando** [korlibs/korio#6]
on Korio 0.6.0, KorRouter.registerRouter is not able to pass params with @Param annotations when a GET request is routed.

As a result, all @Param set in the handler are null, even if that param is set on the http request.

**Comment by soywiz** [comment]
Didn't noticed this. Going to check.

**Comment by soywiz** [comment]
Should be fixed already: https://github.com/korlibs/korio/blob/856f706e157ede113c9939a83d162fe32ffd797e/korio-ext-web/test/com/soywiz/korio/ext/web/router/KorRouterTest.kt#L122
