### ISSUE TITLE
Provide SSL/TLS/HTTPS on native targets

### ISSUE THREAD

**Issue by soywiz** [korlibs/korio#62]
Maybe we can embed boringssl https://boringssl.googlesource.com/boringssl/ or use native facilities on each platform.

* [x] On windows: https://docs.microsoft.com/en-us/windows/win32/winsock/using-secure-socket-extensions - https://github.com/korlibs/korio/issues/143
* [ ] On linux: https://stackoverflow.com/questions/7698488/turn-a-simple-socket-into-an-ssl-socket & https://wiki.openssl.org/index.php/SSL/TLS_Client
* [x] On apple platforms: https://developer.apple.com/documentation/security/secure_transport // https://developer.apple.com/documentation/network

**Comment by Josef-Vonasek** [comment]
Another alternative is `wininet` for windows: https://github.com/localazy/kotlin-mpp-wininet

**Comment by soywiz** [comment]
@Josef-Vonasek do you know the minimum required version of Window for using this API?

Relevant links:
* https://github.com/localazy/kotlin-mpp-wininet/blob/4853faa86937047546a8acaf8f80a0d42168f9e1/src/windowsMain/kotlin/com/localazy/example/http/wininet/WinInetHelper.kt
* https://docs.microsoft.com/es-es/windows/win32/wininet/portal

**Comment by Josef-Vonasek** [comment]
Looks like [Windows 2000 Professional](https://docs.microsoft.com/en-us/windows/win32/api/wininet/nf-wininet-internetreadfile).

**Comment by soywiz** [comment]
But that's for HTTP and FTP only, not for TCP sockets. The idea is to implement a layer to support TLS on all TCP sockets, so everything else works out of the box
