### ISSUE TITLE
Support of Kotlin 1.4-M1

### ISSUE THREAD

**Issue by GitAntoinee** [korlibs/korio#66]
Hello, did you planned Kotlin 1.4-M1?

**Comment by soywiz** [comment]
I'll wait to M2. Related issue: https://github.com/korlibs/klock/issues/101
I would want to use the both mode that has some flaws on M1 yet: https://blog.jetbrains.com/kotlin/2020/03/kotlin-1-4-m1-released/#both-mode

**Comment by soywiz** [comment]
1.12.0 released against Kotlin 1.4
