### ISSUE TITLE
WebSocketClient throws IllegalArgumentException if headers not set

### ISSUE THREAD

**Issue by ArtRoman** [korlibs/korio#81]
korio 1.11.7 introduced nullability check error , possibly caused by #77.
Default values are not passed to constructor if custom headers are not set.

```
GlobalScope.launch {
    WebSocketClient("ws://myserver/")
}
```
```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter headers
	at com.soywiz.korio.net.ws.RawSocketWebSocketClient.<init>(Unknown Source:22)
	at com.soywiz.korio.net.ws.RawSocketWebSocketClientKt.RawSocketWebSocketClient(RawSocketWebSocketClient.kt:28)
	at com.soywiz.korio.net.ws.RawSocketWebSocketClientKt.RawSocketWebSocketClient$default(RawSocketWebSocketClient.kt:23)
	at com.soywiz.korio.net.ws.WebSocketsAndroidKt.WebSocketClient(WebSocketsAndroid.kt:12)
	at com.soywiz.korio.net.ws.WebSocketsAndroidKt.WebSocketClient$default(Unknown Source:0)
	at com.WsTestActivity$onCreate$1$1.invokeSuspend(WsTestActivity.kt:24)

```

**Comment by soywiz** [comment]
Have you cleaned gradle cache when updating korio?

**Comment by ArtRoman** [comment]
> Have you cleaned gradle cache when updating korio?

Yes, the same result after clearing gradle cache and rebuilding project. Korio 1.11.6 is working good, but 1.11.7 and 1.11.8 crashes app. It is reproducible on muliplatform project and on android project, with code example provided in the first comment (there can be any address, it fails just on init).

Moreover, 'headers' field has null value in debugger, as non-null field! It seems to be kotlin bug: IDE uses expect-method with default values, but compiler uses actual-method without default values.

![screenshot 2020-06-11](https://user-images.githubusercontent.com/1625142/84339619-8192ef80-aba7-11ea-9ffc-0ae53fbaa89c.png)

This simple method
```
private suspend fun connect() {
    WebSocketClient("ws://echo.websocket.org")
}
```
compiles into this (decompiled with jadx):
```
 public final /* synthetic */ Object connect(Continuation<? super Unit> $completion) {
    Object WebSocketClient$default = WebSocketsAndroidKt.WebSocketClient("ws://echo.websocket.org", null, null, null, false, null, $completion);
    if (WebSocketClient$default == IntrinsicsKt.getCOROUTINE_SUSPENDED()) {
        return WebSocketClient$default;
    }
    return Unit.INSTANCE;
}
```

As a solution, I can recommend to put default values on actual classes and functions, too.

**Comment by soywiz** [comment]
We are working on the KorGE 1st gamejam, so I cannot fix this now. I will fix this in a couple of weeks, but if you can make a PR fixing this, I can merge it and trigger a release earlier

**Comment by ArtRoman** [comment]
> I can recommend to put default values on actual classes and functions

I was wrong, you can't put default values to actual functions because "Actual function cannot have default argument values, they should be declared in the expected function".

Unfortunately, Kotlin still has issues with default values in expect functions in version 1.3.70+: 
https://youtrack.jetbrains.com/issue/KT-37331,
https://youtrack.jetbrains.com/issue/KT-23890 and some others reports.
They already has this meta-issue https://youtrack.jetbrains.com/issue/KT-38552

**Comment by soywiz** [comment]
What about putting the expect `fun variant without` default parameters, then a non-expect variant with the default parameters?

**Comment by ArtRoman** [comment]
> What about putting the expect `fun variant without` default parameters, then a non-expect variant with the default parameters?

We can't use objects with default values in expect suspend method. 'inline' modifier fixes the issue in simple cases, but I got error `org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: wrong bytecode generated` for WebSocketClient.

Solution is to remove default value from 'headers' param to make it explicit, then add same method without 'headers' field, or without all optional params at all.

As I've tested, these declarations with corresponding implementations in android, jvm, native and js provide the correct behavior:
```
expect suspend fun WebSocketClient(
	url: String,
	protocols: List<String>? = null,
	origin: String? = null,
	wskey: String? = "wskey",
	debug: Boolean = false,
	headers: Http.Headers
): WebSocketClient

expect suspend fun WebSocketClient(
	url: String,
	protocols: List<String>? = null,
	origin: String? = null,
	wskey: String? = "wskey",
	debug: Boolean = false
): WebSocketClient
```

I can make a PR if you wish.
