### ISSUE TITLE
WebSocket: onOpen callback never calls

### ISSUE THREAD

**Issue by ArtRoman** [korlibs/korio#82]
onOpen listener seems to be unusable. Not sure if it bug, because WebSocketClient constructor is suspend. Anyway, I can't set listener to onOpen event without creating an WebSocketClient, but WebSocketClient constructor opens connection immediately in blocking way, and onOpen listener is not still set.

RawSocketWebSocketClient has "connect: Boolean" parameter, but it returns WebSocketClient instance, which hasn't got "connect()" method. RawSocketWebSocketClient has "connect()" method, but it's internal.

```
val ws = WebSocketClient("ws://myserver/")
ws.onOpen.add { 
    throw Exception("onOpen never calls") 
}
```

**Comment by soywiz** [comment]
I think you can execute the onOpen code just after the ws has returned now. I'll think how to do that, since in JS I'm not sure if the onOpen can happen several times if reconnecting, or if you have to reconnect manually
