### ISSUE TITLE
Stop WebSocketClient from sending HTTP GET Request

### ISSUE THREAD

**Issue by benny1611** [korlibs/korio#86]
I need a socket where I can both send and read data from a local server. The problem is whenever I create a new ```WebSocketClient```, it sends a GET Request through the TCP Socket and waits for an answer:

```
GET  HTTP/1.1
Host: localhost:9002
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
Sec-WebSocket-Version: 13
Connection: Upgrade
Sec-WebSocket-Key: bXlrZXk=
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
``` 

How can I stop the ```WebSocketClient``` from doing that?

**Comment by soywiz** [comment]
Then it is not a websocket, that's a plain socket. You can do that on all the targets except on JS Browser. On JS browser the only bidirectional communication channel you can open is thru a websocket
