### ISSUE TITLE
ReferenceError: require is not defined  korio-root-korio.js:47299:3

### ISSUE THREAD

**Issue by benny1611** [korlibs/korio#93]
Hi,

I'm trying to make a multi-platform project and I'm using KorIO version 1.11.10. The project needs to work for both JVM and JS Browser. The problem is when I'm trying to run my project I get this error in the browser's console:
 ```ReferenceError: require is not defined .......... korio-root-korio.js:47299:3```
I'm only using ```WebSockets``` (which are available for both platforms) and also ```com.soywiz.korio.async.delay``` and ```com.soywiz.korio.async.launch```. Are the last 2 not supported for JS Browser? Can you tell me what I'm doing wrong?

Thank you!

**Comment by soywiz** [comment]
Can you tell me what have you in the `build/web/korio-root-korio.js` (if not in that folder, search for korio-root-korio.js in the build folder) at the line `47299` ?

**Comment by benny1611** [comment]
This is the line 47299: ```require_req = require;``` 

[Here](https://ufile.io/5kc7x3y8) is the full file if you want to further investigate the problem.

**Comment by benny1611** [comment]
And [here](https://ufile.io/q4q5fa22) is my ```build.gradle```. I've tried to change the options in ```compileKotlin2Js```, but no luck. Any idea what went wrong?

**Comment by benny1611** [comment]
I've changed my ```build.gradle``` into ```build.gradle.kts``` and also updated the kotlin version, but I still had no luck solving my issue. No matter how I build my project, the file contains a ```require``` in it, that the browser doesn't like. [Here](https://ufile.io/r6ias036) is my ```build.grardle.kts``` file and [here](https://ufile.io/pcl7rhc8) is the output ```korio-root-korio.js``` (this time the problem is on line ```48656```).

**Comment by benny1611** [comment]
Ok, I've done more digging and more changes to my code. I've inspected the generated code. I've tried removing the libs all together. The problem is that the code requires those libs and when I try to run without them I get the message: ```ReferenceError: module is not defined  venus.js:23643:1```, and when I run it with all the libs that it needs I get the same error from above. Am I missing something? [Here](https://ufile.io/npwl676k) is the generated code (```venus.js```)

**Comment by soywiz** [comment]
This might help: https://github.com/korlibs/korio/commit/ccfd7431290598742f8e0916f614966b890260a5

**Comment by benny1611** [comment]
I don't know how to apply this fix? Do I have to build ```korio``` locally? I've tried to change the line from ```require_req = require;``` to ```require_req = lazy(require)```, but I still get the same error.

**Comment by benny1611** [comment]
The problem is now fixed (version ```1.11.11```), thank you! Now I have a different problem, but I will create another issue for that.
